"""
Author : Shrinwas Nayak

Date : 15th Sept 2020
"""

import csv
import datetime

BBSFileName = "Frontrunning_BBS.csv"
BBSFilePath = "/home/shriniwas/UBSProj/input/csvoffrauddata/"

SSBFileName = "Frontrunning_SSB.csv"
SSBFilePath = "/home/shriniwas/UBSProj/input/csvoffrauddata/"

washFileName = "Wash_Trade.csv"
washFilePath = "/home/shriniwas/UBSProj/input/csvoffrauddata/"

reportFileName = "Report.docx"
reportFilePath = "/home/shriniwas/UBSProj/output/"



"""
input : 
function : 
output : 
"""
def openFile(filePath, fileName, mode = "r"):

	fileObj = None

	try:
	
		fileObj = open(filePath + fileName, mode)
		
	except:
	
		print("\n::Unable to open FIle {0}::\n".format(fileName))
		
		exit(1)
		
		
	return fileObj


"""
"""
def writeBasic(reportFileObj):

	reportFileObj.write("\n\t\t\t\tFRAUD DETECTION REPORT\n\n")
	reportFileObj.write("\n\nDate : " + str(datetime.datetime.now()).split(" ")[0] + "\n")
	reportFileObj.write("\n\nThe following report provides a summary of front running and wash trades detected by the system.\n\n\nThis report is generated by the system and the mentioned fraud ids are suggestive and a detailed investigation should be carried out in order to ascertain any wrong doing.\n\n")


"""
"""
def writeWash(reportFileObj, washFileObj):

	reportFileObj.write("\nWASH TRADES\n\n")
	
	tempDateSet = set()
	
	tempBrokerSet = set()
	
	washFraudList = list(washFileObj)
	
	for row in washFraudList[1:]:
	
		tempDateSet.add(row[-1])
		tempBrokerSet.add(row[2])
		
	
	reportFileObj.write("\nThe report presents data for dates : {0}\n\n".format(",".join(tempDateSet)))
	reportFileObj.write("\nTotal {0} wash trades have been detected\n\n".format(len(washFraudList) - 1))
		
	reportFileObj.write("\nList of brokers : \n\n{0}\n\n".format("\n".join(tempBrokerSet)))	

"""
"""
def writeBBS(reportFileObj, BBSFileObj):

	reportFileObj.write("\nBUY-BUY-SELL FRONT RUNNING FRAUDS\n\n")
	
	tempDateSet = set()

	BBSFraudList = list(BBSFileObj)

	idList = []
	
	total = len(BBSFraudList)//3
	
	for row in BBSFraudList[1:]:
	
		tempDateSet.add(row[2])
		idList.append(row[1])
	
	reportFileObj.write("\nThe report presents data for dates : {0}\n\n".format(",".join(tempDateSet)))
	reportFileObj.write("\nTotal {0} BUY-BUY-SELL frauds have been detected\n\n".format(total))
	
	reportFileObj.write("\nFraud Ids are as follows : \n\n{0}\n\n".format(",".join(idList)))
	
	
"""
"""
def writeSSB(reportFileObj, SSBFileObj):

	reportFileObj.write("\nSELL-SELL-BUY FRONT RUNNING FRAUDS\n\n")
	
	tempDateSet = set()

	SSBFraudList = list(SSBFileObj)

	idList = []
	
	total = len(SSBFraudList)//3
	
	for row in SSBFraudList[1:]:
	
		tempDateSet.add(row[2])
		idList.append(row[1])
	
	reportFileObj.write("\nThe report presents data for dates : {0}\n\n".format(",".join(tempDateSet)))
	reportFileObj.write("\nTotal {0} SELL-SELL-BUY frauds have been detected\n\n".format(total))
	
	reportFileObj.write("\nFraud Ids are as follows : \n\n{0}\n\n".format(",".join(idList)))
		

#MAIN


reportFileObj = openFile(reportFilePath, reportFileName, "w")

writeBasic(reportFileObj)

washFileObj = csv.reader(openFile(washFilePath, washFileName, "r"))
BBSFileObj = csv.reader(openFile(BBSFilePath, BBSFileName, "r"))
SSBFileObj = csv.reader(openFile(SSBFilePath, SSBFileName, "r"))


writeBBS(reportFileObj, BBSFileObj)
writeSSB(reportFileObj, SSBFileObj)
writeWash(reportFileObj, washFileObj)


